apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-phpfpm
  labels:
    app: demo-app-phpfpm
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: demo-app-phpfpm
  template:
    metadata:
      labels:
        app: demo-app-phpfpm
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.php.repository }}:{{ .Values.image.php.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.php.pullPolicy }}
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 30
          ports:
            - containerPort: 9000
          env:
            {{- range $name, $value := .Values.environments }}
            - name: {{ $name | quote }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $secret := .Values.secrets }}
            - name: {{ $secret.name | quote }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secret.secretKeyRefName }}
                  key:  {{ $secret.secretKeyRefKey }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 1
            timeoutSeconds: 5
            periodSeconds: 60
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 1
            timeoutSeconds: 5
            periodSeconds: 60
            failureThreshold: 3
            successThreshold: 1
          resources:
{{ toYaml .Values.resources.phpfpm | nindent 12 }}
