image:
  php:
    repository: 'gcr.io/dnmz-dimostration/symfony-cloudrun'
    pullPolicy: IfNotPresent
    tag: 'latest'
  nginx:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: 1.20.2

environments:
  APP_ENV: prod
  APP_SECRET: 'secret'


resources:
  phpfpm:
    limits:
      cpu: 400m
      memory: 256Mi
    requests:
      cpu: 400m
      memory: 256Mi
  nginx:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 64Mi
